FROM pihole/pihole:latest

ENV ADMIN_EMAIL="rolly@awang.ga"
ENV TZ="Asia/Jakarta"
ENV WEBPASSWORD="rollyganteng"
#RUN rm /etc/nginx/sites-enabled/app.conf

#COPY ./etc-pihole/ ./etc/pihone/
#COPY ./etc-dnsmasq.d /etc/dnsmasq.d/
