git clone git@gitlab.com:viralbisnis/scheduler-expire.git
git clone git@gitlab.com:viralbisnis/notifikasi-resender.git
git clone git@gitlab.com:viralbisnis/natsserver.git
git clone git@gitlab.com:viralbisnis/mutasi-bank.git
git clone git@gitlab.com:viralbisnis/minio.git
git clone git@gitlab.com:viralbisnis/n11_apiproxy.git
git clone git@gitlab.com:viralbisnis/n18_webproxy.git
git clone git@gitlab.com:viralbisnis/natsclient.git
git clone git@gitlab.com:viralbisnis/shopapidata.git
git clone git@gitlab.com:viralbisnis/apiowner.git
git clone git@gitlab.com:viralbisnis/api-integration.git
git clone git@gitlab.com:viralbisnis/member-api-data.git
git clone git@gitlab.com:viralbisnis/admin-api-data.git
git clone git@gitlab.com:viralbisnis/ws.git
git clone git@gitlab.com:viralbisnis/apiblog.git
git clone git@gitlab.com:viralbisnis/apishop.git
git clone git@gitlab.com:viralbisnis/apisuperadmin.git
git clone git@gitlab.com:viralbisnis/apiadmin.git
git clone git@gitlab.com:viralbisnis/apimember.git
git clone git@gitlab.com:viralbisnis/superadmin.git
git clone git@gitlab.com:viralbisnis/admin.git
git clone git@gitlab.com:viralbisnis/onlineshop.git
git clone git@gitlab.com:viralbisnis/owner.git
git clone git@gitlab.com:viralbisnis/member.git