#!/bin/bash

openssl genrsa -des3 -out $1.key 4096
openssl req -new -key $1.key -out $1.csr
openssl x509 -req -days 700 -in $1.csr -signkey $1.key -out $1.crt
cp $1.crt /etc/httpd/ssl/
cp $1.key /etc/httpd/ssl/
echo "please edit virtual host to use ssl and restart the web server"